"""empty message

Revision ID: 09fdcefbe168
Revises: 15d296113901
Create Date: 2018-06-10 13:15:32.031591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09fdcefbe168'
down_revision = '15d296113901'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('language', sa.String(length=5), nullable=True))
    op.add_column('post', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.add_column('post', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_post_timestamp'), 'post', ['timestamp'], unique=False)
    op.create_foreign_key(None, 'post', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_index(op.f('ix_post_timestamp'), table_name='post')
    op.drop_column('post', 'user_id')
    op.drop_column('post', 'timestamp')
    op.drop_column('post', 'language')
    # ### end Alembic commands ###
