"""empty message

Revision ID: 0ab0ce191512
Revises: eae4e89f7a54
Create Date: 2018-06-12 19:56:26.942704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ab0ce191512'
down_revision = 'eae4e89f7a54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todotask',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('todo_name', sa.String(length=255), nullable=True),
    sa.Column('todo_priority', sa.String(length=10), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_todotask_due_date'), 'todotask', ['due_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_todotask_due_date'), table_name='todotask')
    op.drop_table('todotask')
    # ### end Alembic commands ###
