"""empty message

Revision ID: 784137460409
Revises: f287055677c4
Create Date: 2018-06-12 13:10:34.847193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '784137460409'
down_revision = 'f287055677c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'posted_by')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('posted_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
