"""empty message

Revision ID: a3b0ab80eed9
Revises: d9e26cafffa9
Create Date: 2018-06-26 19:52:14.879950

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a3b0ab80eed9'
down_revision = 'd9e26cafffa9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todotask', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_todotask_timestamp'), 'todotask', ['timestamp'], unique=False)
    op.drop_index('ix_todotask_date', table_name='todotask')
    op.drop_column('todotask', 'date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todotask', sa.Column('date', mysql.DATETIME(), nullable=True))
    op.create_index('ix_todotask_date', 'todotask', ['date'], unique=False)
    op.drop_index(op.f('ix_todotask_timestamp'), table_name='todotask')
    op.drop_column('todotask', 'timestamp')
    # ### end Alembic commands ###
