"""empty message

Revision ID: e0fc8eef1853
Revises: 1afdc989a301
Create Date: 2018-06-17 20:14:49.607505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0fc8eef1853'
down_revision = '1afdc989a301'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assignments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('base', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('due_at', sa.DateTime(), nullable=True),
    sa.Column('unlock_at', sa.DateTime(), nullable=True),
    sa.Column('lock_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assignments_title'), 'assignments', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assignments_title'), table_name='assignments')
    op.drop_table('assignments')
    # ### end Alembic commands ###
